### ISSUE TITLE
shazamio.exceptions.FailedDecodeJson: Failed to decode json

### ISSUE THREAD

**Issue by cc00010** [shazamio/ShazamIO#104]
Hello, I can't use shazamio methods, it says:
```
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.shazam.com/shazam/v3/en-US/GB/web/-/tracks/ip-country-chart-UZ?pageSize=20&startFrom=0')
```

Code:
`shazam.top_country_tracks("US", offset=0, limit=2)`

**Comment by dotX12** [comment]
I’m not even surprised how at the same time this function stopped working in all rapidapi, which present a wrapper for Shazam and charge money for it (after all, they just use this project): DDD

I’m in the process of fixing it, there’s a lot of stuff at my main job, I’ll try to fix it by evening, I already understand how it can be done.

**Comment by dotX12** [comment]
Congratulations to all developers and separately developers for RapidAPI, the fix has been added.
Thx @cc00010!

Version 0.6.0 released.
https://pypi.org/project/shazamio/0.6.0/
