### ISSUE TITLE
load on the processor.

### ISSUE THREAD

**Issue by masksshow** [shazamio/ShazamIO#12]
Hi. Great project.
You can tell why recognition is causing such a heavy load on the processor.
I am sending a file of 500 kb, this is enough for the detection, but the CPU load is huge at the moment of recognition.
Can the load be reduced? Does it depend on the file format for recognition?
Thanks!

**Comment by dotX12** [comment]
@masksshow, 
Unfortunately, I don't have much time to check it myself.
If you have the time and opportunities, check it out and do a PR.

**Comment by dotX12** [comment]
* https://github.com/dotX12/ShazamIO/pull/32 - Partial solution to the problem.

**Comment by dotX12** [comment]
https://github.com/dotX12/ShazamIO/issues/78

**Comment by dotX12** [comment]
Closed, problem fixed.
https://github.com/shazamio/ShazamIO/issues/76#issuecomment-1961610344
