### ISSUE TITLE
Album song count

### ISSUE THREAD

**Issue by Janphr** [shazamio/ShazamIO#42]
Hey,

thanks for this! :)

could you tell me what'd be the best way to get the album song count of a recognized track?
I can see the album in the metadata list under sections. But is there a way to look up the album and get the amount of songs on that album?

Thanks!

**Comment by dotX12** [comment]
@Janphr, https://www.shazam.com/services/amapi/v1/catalog/ru/artists/503131736/albums
![image](https://user-images.githubusercontent.com/64792903/206786231-efefd1d7-8dec-471e-9c54-bd43a6d9dbbd.png)
I plan to add this functionality over the weekend.

**Comment by dotX12** [comment]
And: https://www.shazam.com/services/amapi/v1/catalog/ru/albums/1650765462
@Janphr

**Comment by Janphr** [comment]
That works for me, thanks!

**Comment by dotX12** [comment]
I've been sorting through my other open projects, I'll add methods for current requests soon.

**Comment by dotX12** [comment]
added in 0.5.0.
