### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by lunoxis** [shazamio/ShazamIO#63]
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8',

**Comment by captain-cronch** [comment]
What code are you running that results in this error?

**Comment by dotX12** [comment]
@lunoxis, hi, thanks for creating the issue, but it would be great if you could attach an example of the code that leads to it, because apart from the fact that there was an exception when trying to make response.json(), I don't see anything.

**Comment by lunoxis** [comment]
> @lunoxis, hi, thanks for creating the issue, but it would be great if you could attach an example of the code that leads to it, because apart from the fact that there was an exception when trying to make response.json(), I don't see anything.

hi 
import asyncio
from shazamio import Shazam


async def main():
  shazam = Shazam()
  out = await shazam.recognize_song('dora.ogg')
  print(out)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

**Comment by lunoxis** [comment]
> > > @lunoxis, hi, thanks for creating the issue, but it would be great if you could attach an example of the code that leads to it, because apart from the fact that there was an exception when trying to make response.json(), I don't see anything.
> > 
> > 
> > hi import asyncio from shazamio import Shazam
> > async def main(): shazam = Shazam() out = await shazam.recognize_song('dora.ogg') print(out)
> > loop = asyncio.get_event_loop() loop.run_until_complete(main())
> > python3.8.10
> 
> do u installed ffmpeg and ffprobe?

yes,ffmpeg 1.4

**Comment by lunoxis** [comment]
> > > @lunoxis, hi, thanks for creating the issue, but it would be great if you could attach an example of the code that leads to it, because apart from the fact that there was an exception when trying to make response.json(), I don't see anything.
> > 
> > 
> > hi import asyncio from shazamio import Shazam
> > async def main(): shazam = Shazam() out = await shazam.recognize_song('dora.ogg') print(out)
> > loop = asyncio.get_event_loop() loop.run_until_complete(main())
> > python3.8.10
> 
> do u installed ffmpeg and ffprobe?

bro can you help me?
