### ISSUE TITLE
Can we access the database?

### ISSUE THREAD

**Issue by durgesh17medi** [shazamio/ShazamIO#79]
Hi, thanks for the great project, it works just perfectly. I was wondering is there a way we can access the database of original song fingerprints so that if any song fingerprint is not available in the db we can generate the fingerprint for the same,  and update the db?

**Comment by dotX12** [comment]
> Hi, thanks for the great project, it works just perfectly. I was wondering is there a way we can access the database of original song fingerprints so that if any song fingerprint is not available in the db we can generate the fingerprint for the same, and update the db?

Hello, to be honest, I don't know :)
