### ISSUE TITLE
dependency conflicts.

### ISSUE THREAD

**Issue by jm7uz** [shazamio/ShazamIO#84]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
aiogram 3.3.0 requires aiofiles~=23.2.1, but you have aiofiles 22.1.0 which is incompatible.
aiogram 3.3.0 requires pydantic<2.6,>=2.4.1, but you have pydantic 1.10.14 which is incompatible.

**Comment by DiyorbekAhmadjonov** [comment]
> Xato: pip's dependency resolver hozirda o'rnatilgan barcha paketlarni hisobga olmaydi. Ushbu xatti-harakatlar quyidagi qaramlik ziddiyatlarining manbai hisoblanadi. aiogram 3.3.0 aiofiles~ = 23.2.1 talab qiladi, lekin sizda aiofiles 22.1.0 mos kelmaydi. aiogram 3.3.0 pydantic talab < 2.6,>=2.4.1, lekin siz pydantic bor 1.10.14 qaysi mos kelmaydigan.

I recommend running shazam as a separate api
