### ISSUE TITLE
Does shazamio work with audio playing from URL instead of a file?

### ISSUE THREAD

**Issue by ut21** [shazamio/ShazamIO#87]
I want to detect the music playing on some URL (an IceCast stream for example), is there a way to do that? Running the following code gives FileNotFoundError: [Errno 2] No such file or directory: 'http://<URL>' :

```python
async def main():
    shazam = Shazam()
    out = await shazam.recognize_song('http://<URL>')
    print(out)```

**Comment by dotX12** [comment]
Currently you can either transfer the bytes or download the file and transfer the file path.
