### ISSUE TITLE
Ошибка recognize_song()

### ISSUE THREAD

**Issue by Progi0** [shazamio/ShazamIO#93]
Выводит ошибку:
FileNotFoundError: [WinError 2] Не удается найти указанный файл

Проверил, файл указан верно. Помогите пожалуйста с такой странной проблемой
![Снимок экрана 2024-02-20 220648](https://github.com/shazamio/ShazamIO/assets/160604885/1d94bfbf-e00e-4807-a049-20483cc1dab3)

**Comment by dotX12** [comment]
@Progi0, установлен ли ffmpeg?

**Comment by chikpikmik** [comment]
У меня такая же ошибка, но импорт не помог((
![image](https://github.com/shazamio/ShazamIO/assets/90050790/9ec1be6d-ba0d-40ae-bcec-c5ac18150f67)

  File "C:\Users\cildr\anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by dotX12** [comment]
> У меня такая же ошибка, но импорт не помог(( ![image](https://private-user-images.githubusercontent.com/90050790/306938748-9ec1be6d-ba0d-40ae-bcec-c5ac18150f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTQ1NTUsIm5iZiI6MTcwODU5NDI1NSwicGF0aCI6Ii85MDA1MDc5MC8zMDY5Mzg3NDgtOWVjMWJlNmQtYmEwZC00MGFlLWJjZWMtYzVhYzE4MTUwZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA5MzA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NTllMWU1NjM0ZjZkYzVmMzBlYWIwNTg5NzFkZDg2MmM4YjczOWYxOWFmNTkyMmQ4ZjQ2M2Y4ZGJjOGFmOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FmvZBMN6MN3OoQ1wTwJBhG7nYgMUaW3N6PeGIRVa1XM)
> 
> File "C:\Users\cildr\anaconda3\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> 
> FileNotFoundError: [WinError 2] Не удается найти указанный файл

привет, ffmpeg установи и добавь в PATH

**Comment by Progi0** [comment]
> У меня такая же ошибка, но импорт не помог(( ![изображение](https://private-user-images.githubusercontent.com/90050790/306938748-9ec1be6d-ba0d-40ae-bcec-c5ac18150f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTM2NDksIm5iZiI6MTcwODYxMzM0OSwicGF0aCI6Ii85MDA1MDc5MC8zMDY5Mzg3NDgtOWVjMWJlNmQtYmEwZC00MGFlLWJjZWMtYzVhYzE4MTUwZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE0NDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYjNjZDI1Y2RjMGI0ZmUyNWM4NTdiNWZkMWY5OWUwNzg3Y2EwMjg4ZjhmMWEwODY5MGFjMzc5NDYxMGFmNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5PEStMcQTe1a659BenGSBAQekko9YeULkDzKFFvm7c)
> 
> Файл "C:\Users\cildr\anaconda3\lib\subprocess.py", строка 1420, в _execute_child hp, ht, pid, tid = _winapi.CreateProcess(исполняемый файл, аргументы,
> 
> FileNotFoundError: [WinError 2] Не удается найти указанный файл

Используй в терминале эти 2 команды для установки ffmpeg:
 ffdl install --add-path  
pip install ffmpeg-downloader  

Напиши обязательно что вышло.

**Comment by chikpikmik** [comment]
> > У меня такая же ошибка, но импорт не помог(( ![изображение](https://private-user-images.githubusercontent.com/90050790/306938748-9ec1be6d-ba0d-40ae-bcec-c5ac18150f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTM2NDksIm5iZiI6MTcwODYxMzM0OSwicGF0aCI6Ii85MDA1MDc5MC8zMDY5Mzg3NDgtOWVjMWJlNmQtYmEwZC00MGFlLWJjZWMtYzVhYzE4MTUwZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE0NDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYjNjZDI1Y2RjMGI0ZmUyNWM4NTdiNWZkMWY5OWUwNzg3Y2EwMjg4ZjhmMWEwODY5MGFjMzc5NDYxMGFmNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5PEStMcQTe1a659BenGSBAQekko9YeULkDzKFFvm7c)
> > Файл "C:\Users\cildr\anaconda3\lib\subprocess.py", строка 1420, в _execute_child hp, ht, pid, tid = _winapi.CreateProcess(исполняемый файл, аргументы,
> > FileNotFoundError: [WinError 2] Не удается найти указанный файл
> 
> Используй в терминале эти 2 команды для установки ffmpeg: ffdl install --add-path pip install ffmpeg-downloader
> 
> Напиши обязательно что вышло.

![image](https://github.com/shazamio/ShazamIO/assets/90050790/f67b04c8-2389-49e5-b26e-cc0224966da3)
![image](https://github.com/shazamio/ShazamIO/assets/90050790/8dbf78b5-9ae0-41c5-ba7b-32a4e20ae37c)
C:\Users\Lolban\Projects\TestingHere\venv\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\Lolban\Projects\TestingHere\venv\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\Lolban\Projects\TestingHere\shz\shazamio_prog.py", line 12, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Lolban\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lolban\Projects\TestingHere\shz\shazamio_prog.py", line 8, in main
    out = await shazam.recognize_song(f.read())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lolban\Projects\TestingHere\venv\Lib\site-packages\shazamio\api.py", line 347, in recognize_song
    song = await get_song(data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lolban\Projects\TestingHere\venv\Lib\site-packages\shazamio\utils.py", line 42, in get_song
    return AudioSegment.from_file(BytesIO(data))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lolban\Projects\TestingHere\venv\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lolban\Projects\TestingHere\venv\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lolban\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Lolban\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by dotX12** [comment]
@chikpikmik https://www.ffmpeg.org/download.html#build-windows 
Установи ffmpeg по инструкции.
